---

- name: "Verify {{ app_name }} objects removed"
  set_fact:
    ca_secret: "{{ ca_secret_lookup }}"
    admin_secret: "{{ admin_secret_lookup }}"
    user_secret: "{{ user_secret_lookup }}"
    init_configmap: "{{ init_configmap_lookup }}"
    mongodb_configmap: "{{ mongodb_configmap_lookup }}"
    poddisruptionbudget: "{{ poddisruptionbudget_lookup }}"
    statefulset: "{{ statefulset_lookup }}"
    service: "{{ service_lookup }}"
  retries: 10
  delay: 5
  until:
    - not ca_secret_lookup
    - not admin_secret_lookup or (auth_enabled and auth_existingAdminSecret is undefined)
    - not user_secret_lookup or (auth_enabled and auth_existingUserSecret is undefined)
    - not init_configmap_lookup
    - not mongodb_configmap_lookup
    - not poddisruptionbudget_lookup or not (podDisruptionBudget is defined and (podDisruptionBudget | from_yaml))
    - not statefulset_lookup
    - not service_lookup


- name: "Verify statefulset persistentvolumeclaim objects removed"
  shell: kubectl get persistentvolumeclaim {{ item }}
  register: kubectl_cmd
  failed_when: kubectl_cmd.rc == 0 or kubectl_cmd.rc >= 2
  with_items: "{{ statefulset_pvcs }}"
