---

- name: "Verify {{ name }} objects exist"
  set_fact:
    ca_secret: "{{ ca_secret_lookup }}"
    admin_secret: "{{ admin_secret_lookup }}"
    user_secret: "{{ user_secret_lookup }}"
    init_configmap: "{{ init_configmap_lookup }}"
    mongodb_configmap: "{{ mongodb_configmap_lookup }}"
#    poddisruptionbudget: "{{ poddisruptionbudget_lookup }}"
    statefulset: "{{ statefulset_lookup }}"
    service: "{{ service_lookup }}"

  retries: 20
  delay: 10
  until:
    - ca_secret_lookup or not tls_enabled
    - admin_secret_lookup or not auth_enabled
    - user_secret_lookup or not auth_enabled
    - init_configmap_lookup
    - mongodb_configmap_lookup
#    - poddisruptionbudget_lookup or not (podDisruptionBudget is defined and (podDisruptionBudget | from_yaml))
    - statefulset_lookup
    - service_lookup

# Work-around for https://github.com/kubernetes-client/python/issues/466
- name: "Verify podisruptionbudget exists"
  shell: kubectl get poddisruptionbudget {{ name }} -n {{ namespace }}
  when: podDisruptionBudget is defined and (podDisruptionBudget | from_yaml)


- name: "Wait for statefulset to become ready"
  debug:
    msg: "StatefulSet ready status: {{ statefulset_query }}"
  retries: 60
  delay: 10
  until:
    - statefulset_query


- name: "set fact statefulset pvcs state={{ state }}"
  include_tasks: "set_fact_statefulset_pvcs.yml"


- name: "Verify statefulset persistentvolumeclaims exist"
  shell: kubectl get persistentvolumeclaim {{ item }} -n {{ namespace }}
  with_items: "{{ statefulset_pvcs }}"
