---

# Defaults for values we could expect from a broker

_apb_plan_id: default
_apb_service_class_id: 0
_apb_service_instance_id: 0

default_debug: True
bootstrap_debug_enabled: False

apb_name: nuxeo-arender-apb
app_image: docker.io/nuxeoapbcatalog/nuxeo-arender-apb
namespace: "{{ lookup('env','NAMESPACE') | default('hello-world', true) }}"

testing: false


project_name: minio
minio_image: minio/minio
minio_image_version: latest
minio_mode: Standalone
minio_nodes: 4
minio_size: 5

image_pullPolicy: IfNotPresent
podAnnotations: '{}'
securityContext: '{}'
resources: '{"limits": {"cpu": "1","memory": "512Mi"},"requests": {"cpu": "0.5","memory": "256Mi"}}'