---
app_name: kibana

# Defaults for values we could expect from a broker

_apb_plan_id: default
_apb_service_class_id: 0
_apb_service_instance_id: 0

default_debug: True
bootstrap_debug_enabled: False

apb_name: nuxeo-kibana-apb
app_image: docker.io/nuxeoapbcatalog/nuxeo-kibana-apb
namespace: "{{ lookup('env','NAMESPACE') | default('hello-world', true) }}"

testing: false
kibana_image: docker.elastic.co/kibana/kibana-oss
kibana_image_version: "6.3.2"
kibana_memory_limit: 256Mi
kibana_pvc_size: 200Mi
kibana_secure: "true"
kibana_storage_plan: "ephemeral"
