- name: nuxeo-mongo-apb bind
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-mongodb-apb-binding
  vars:
    apb_action: bind
