---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster


- name: "Configure monitoring stack"
  include_tasks: "monitoring.yml"
  when: arender_rendition_monitoring_enabled

- name: "Creating Stack Service Account"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'arender_rendition_sa.yml.j2') | from_yaml }}"


- name: "Set PVC {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'arender_pvc.yml.j2') | from_yaml }}"
  loop:
    - pvc_name: "{{ arender_rendition_broker_pvc_name }}"
    - pvc_name: "{{ arender_common_tmp_name }}"
    - pvc_name: "{{ arender_logs_pvc_name }}"


- name: "Set Log config {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'arender_log_config.yml.j2') | from_yaml }}"
  loop:
    - name: "{{ arender_converter_log_configmap_name }}"
      file: arender_converter_logback.xml
    - name: "{{ arender_dfs_log_configmap_name }}"
      file: arender_dfs_logback.xml
    - name: "{{ arender_jni_log_configmap_name }}"
      file: arender_jni_logback.xml
    - name: "{{ arender_pdfbox_log_configmap_name }}"
      file: arender_pdfbox_logback.xml
    - name: "{{ arender_broker_log_configmap_name }}"
      file: arender_broker_logback.xml


- name: "Set ARender objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: arender_rendition_sa.yml.j2
    - name: arender_rendition_pull_secret.yml.j2
      apply: "{{ create_pull_secret }}"
    - name: arender_converter_dc.yml.j2
    - name: arender_converter_service.yml.j2
    - name: arender_dfs_dc.yml.j2
    - name: arender_dfs_service.yml.j2
    - name: arender_jni_dc.yml.j2
    - name: arender_jni_service.yml.j2
    - name: arender_pdfbox_dc.yml.j2
    - name: arender_pdfbox_service.yml.j2
    - name: arender_broker_dc.yml.j2
    - name: arender_broker_service.yml.j2
    - name: arender_debug_dc.yml.j2
      apply: "{{ arender_debug_pod == true }}"


- name: "Set Autoscaling objects {{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'arender_autoscaling.yml.j2') | from_yaml }}"
  loop:
    - name: converter
      target_dc: "{{ arender_converter_dc_name }}"
    - name: pdfbox
      target_dc: "{{ arender_pdfbox_dc_name }}"
    - name: jni
      target_dc: "{{ arender_jni_dc_name }}"
    - name: broker
      target_dc: "{{ arender_broker_dc_name }}"




- name: "Wait for Rendition Deployment to become ready"
  debug:
    msg: "DeploymentConfig ready status: {{ arender_converter_dc_query }}"
  retries: 50
  delay: 10
  until:
    - arender_broker_dc_query
    - arender_converter_dc_query
    - arender_dfs_dc_query
    - arender_jni_dc_query
    - arender_pdfbox_dc_query
  when: state == 'present'


- name: encode bind credentials
  asb_encode_binding:
    fields:
      app_name: "{{ name }}"
      broker_service_dns: "{{ arender_broker_service_name }}.{{ namespace }}.svc"
      broker_service_url: "http://{{ arender_broker_service_name }}.{{ namespace }}.svc:{{ arender_broker_internal_port}}/"
      broker_service_port: "{{ arender_broker_internal_port}}"
  when:
    - state == "present"
    - in_cluster


- name: "Update last operation"
  asb_last_operation:
    description: "100%: Cluster objects state={{ state }}"
  when: in_cluster